create a login mutation
indigotech/onboard-matheus-santana pull request #23
Opened 2024-09-13 12:12 UTC by Matheus22032

Criando a login mutaation e seu test case

2024-09-13 12:32 UTC, matheusflds requested changes

2024-09-13 12:32 UTC, matheusflds commented on test/login-mutation-test.ts
> +  const graphqlMutatitonGenereted = (email: string, password: string) => {
acredito que poderia dar uma melhorada no nome, algo como `buildLoginMutationInput` por exemplo, para deixar mais claro o proposito da função, via de regra tentaria buscar nomear com verbos e outros recursos para indicar a execução da ação, `graphlQLMutationGenerated` tá mais para o resultado de uma função

2024-09-13 12:32 UTC, matheusflds commented on test/login-mutation-test.ts
> +      .data.createUser;
você está acoplando o teste de uma chamada com outra, assim como os its devem ser atômicos, os testes das chamadas também não devem estar acoplados a outras, já temos testes para a mutation de criar o usuário, o teste de login não deveria executar esse fluxo novamente

motivações:
- a criação pode ter um "setup" maior e vai precisar trazer mais código pra ca (por exemplo, ao invés de criar o usuario no banco, o server poderia chamar uma outra api do cliente)
- erros e complexidades do fluxo de criar usuário estão vindo para esse teste do login, além de afetar no entendimento do código pode ficar meio problemático de dar manutenção se vc seguir isso pra todos os arquivos e mudar alguma coisa na mutation de criar usuario

sugestão:
- criar o usuário "na mão" usando o prisma msm, dado que ja temos o teste de createUser, podemos considerar que aqui ja teria um usuario criado sem problemas

Faz sentido?

2024-09-13 12:43 UTC, Matheus22032 commented on test/login-mutation-test.ts
> +      .data.createUser;
faz sentido, na hora tive bastante dificuldade de pensar o fluxo deese teste

2024-09-13 16:55 UTC, matheusflds approved these changes

2024-09-16 14:09 UTC, alanraso approved these changes

2024-09-16 16:21 UTC, merged